<?php include "includes/header.php"?>

<div>
    <p class="bio">Singing is an unconventional instrument that requires an equal balance and high level competencies of kinesthetic, aural, visual, and tactile learning modes. As a result, learning to sing is one of the most emotional, introspective, and vulnerable activity that humans can attempt. In his book, <i>Singing and Imagination,</i> Thomas Hemsley says “The impulse to sing, then, in our tradition, is not simply the wish to make a sweet sound, or a loud sound— or indeed to “make” any sort of sound; it is the overwhelming urge to express feelings.” My entire teaching philosophy is to foster technique and understanding of each vocal instrument through a variety of specific exercises, imagery, and physical movement, but never ignoring the most important component of singing: emotion. I am a firm believer that an intuitive and artistic singer is built from a person who can connect to a composer’s work from in impassioned standpoint. Discovering an inspiration to sing is the key to finding a vocalist’s true voice.</p>

    <p class="bio">The unique fact about the vocal mechanism is that there are no two instruments alike. This is precisely why it can be terrifying to sing—we are virtually blind to the instrument. It is important for me to help my students realize that their vocal instrument is one-of-a-kind and that their sound is indeed worthy enough to be heard. True potential and individuality is what I encourage each of my students to discover about themselves as people and musicians. I am committed to helping and identifying the needs of each singer while creating a curriculum to harness their strongest learning style and improving their weaker abilities. I encourage their awareness as a musician, actor, and communicator in an effort to realize their artistry.</p>
    
    <p class="bio">Vocally, I include the following subjects with every student: relaxation, posture and alignment, breathing, phonation, support, registration, resonance, and articulation. I am vocal about every student’s sense of achievement and success, and I encourage them to take time outside of the studio to recreate our lessons in an effort to harness correct vocal habits. I am committed to explaining each subject in a way that helps their process of learning. I assign clear objectives of each lesson, specific vocalises to aid in the musculature strength of the vocal folds and surrounding tissue, visualization exercises, and I provide each student with vocal literature that addresses their specific needs. As for repertoire, there is never a “one song fits all” attitude toward my teaching and I am constantly looking for new and appropriate repertoire for each student. While learning these various skills I help the student gain physical awareness of their body so that they can sing without inhibition.</p>
    
    <p class="bio">I find language to be an important technique when helping my students understand that using the proper language in singing can only benefit their sound. The correct unification of vowels and consonants to specific sounds is important for every singer to accomplish. I have an extensive knowledge of the International Phonetic Alphabet (IPA) and have taken courses in Italian and French. I am comfortable teaching English, French, German, and Italian diction and understand the differences between each language.</p>
    
    <p class="bio">My diverse background in music, includes commercial techniques, musical theater, art song, and opera. This allows me to comfortably teach a huge variety of vocal styles. Having a Bachelor and Master of Music with contrary vocal emphases has allowed me to understand the vocal demands and techniques that are affiliated with not only classical music, but musical theater singing and commercial styles. With the demands of the stage today, not only do these singers need to understand how to produce a healthy tone that is rooted in classical vocal pedagogy, but they also need to understand how to relinquish the rounded sounds of classical technique and apply them to the brighter commercial techniques without damaging their vocal mechanism. With this education, it has become imperative for me to stress the importance of vocal health to every student. Ensuring that each singer knows how their vocal mechanism scientifically works is also a key point in my teaching. I keep up to date on the latest vocal science activity, as well as vocal treatises of the past.</p>

    <p class="bio">My own experience of singing and studying multiple vocal styles, while being a singing actor myself, has given me the chance to help musical theater, commercial vocalists, and classical singers find their own voices in a healthy and informed way. As an educator, I find it beneficial and rewarding to treat each vocalist as their mentor and collaborator in an effort to invigorate their commitment to the music. Quality and artistry is always achieved from the passionate musician.</p>
</div>

</div>
<?php include "includes/footer.php"?>